#!/usr/bin/ruby
##############################################
# Author: James M Snell (jasnell@gmail.com)  #
# License: Apache v2.0                       #
##############################################
require 'streams'
require 'optparse'

options = {}
optparse = OptionParser.new do|opts|
 opts.banner = "Usage: note [options] content"
 options[:name] = nil
 opts.on( '-n', '--name NAME', 'The name' ) do |x|
   options[:name] = x
 end
 opts.on( '-h', '--help', 'Display this screen' ) do
   puts opts
   exit
 end
end
optparse.parse!

include ActivityStreams
 
STDOUT << activity {
  pretty
  verb :post
  actor person {
    display_name options[:name]
  }
  obj note {
    content ARGV.shift
    attachment binary {
      # binary attachments are base64 and compressed automatically for you
      data 'activity_note' # will use deflate compression and generate md5 hash by default
    }
  }
  img {
    url 'http://example.org'
  }
  location {
    position {
      longitude 180
      latitude -56.32
    }
  }
}
